# Generated by Django 5.0.3 on 2024-04-19 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tv_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user',
            new_name='the_user',
        ),
    ]
