# Generated by Django 5.0.3 on 2024-04-13 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tv_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='description',
            field=models.TextField(default=0.0004940711462450593),
            preserve_default=False,
        ),
    ]
