# Generated by Django 5.0.3 on 2024-04-16 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tv_app', '0003_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='show',
            old_name='description',
            new_name='comment',
        ),
    ]
