# Generated by Django 5.0.3 on 2024-04-16 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tv_app', '0006_alter_show_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(default=0.0004970178926441351, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='tv_app.user'),
            preserve_default=False,
        ),
    ]
