# Generated by Django 5.0.3 on 2024-04-16 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tv_app', '0007_comment_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
    ]
